image_width: 1280
image_height: 720
camera_name: camera_color
camera_matrix:
  rows: 3
  cols: 3
  data: [732.24682,   0.     , 639.06338,
           0.     , 730.78505, 339.62165,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.039311, -0.066984, -0.001459, -0.004972, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [724.43653,   0.     , 629.52647,   0.     ,
           0.     , 737.05013, 338.49225,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
