image_width: 640
image_height: 576
camera_name: camera_ir
camera_matrix:
  rows: 3
  cols: 3
  data: [495.95227,   0.     , 334.50096,
           0.     , 496.37263, 326.03938,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.345785, 0.117554, 0.001043, 0.001500, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [413.00473,   0.     , 342.47617,   0.     ,
           0.     , 426.27811, 339.14052,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
